# Generated by Django 4.1.7 on 2023-04-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='writer_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
