# Generated by Django 4.1.7 on 2023-04-23 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0003_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='writer_name',
        ),
        migrations.AddField(
            model_name='book',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookApp.writer'),
        ),
    ]
