# Generated by Django 4.1.7 on 2023-04-23 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0005_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='user_name',
        ),
    ]
