# Generated by Django 4.2 on 2023-04-23 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0006_rename_user_user_user_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
