# Generated by Django 4.2 on 2023-04-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0008_alter_users_password_alter_users_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='firstName',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='FavBookCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_name', models.CharField(max_length=50, unique=True)),
                ('book_name', models.ManyToManyField(to='bookApp.book')),
            ],
        ),
    ]
