# Generated by Django 4.2 on 2023-04-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0008_alter_users_password_alter_users_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='firstName',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='lastName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
