# Generated by Django 4.2 on 2023-04-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0009_alter_book_name_alter_writer_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
