# Generated by Django 4.2 on 2023-04-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0013_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='dob',
            field=models.DateField(max_length=9, null=True),
        ),
    ]
