# Generated by Django 4.2 on 2023-04-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0014_writer_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
