# Generated by Django 4.2 on 2023-04-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0015_alter_writer_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date',
        ),
        migrations.AddField(
            model_name='book',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
