# Generated by Django 4.2 on 2023-04-28 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0017_alter_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image',
            new_name='book_Img',
        ),
    ]
